# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('task', models.CharField(max_length=32)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mana.UserInfo')),
            ],
        ),
    ]
